version: '2'
services:
  firefox:
    image: selenium/standalone-firefox
    container_name: firefox
    ports:
      - "4444:4444"
  tests:
    build: .
    container_name: tests
    command: rspec
    links:
      - firefox

